#!/usr/bin/env bash
#Update package lists and Install nginx
apt-get update
apt-get install -y nginx
echo "Hello World!" > /etc/nginx/html/index.html
#echo nginx to listen on port 80
echo "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default
service nginx reload
