#!/usr/bin/env bash
#script that displays Best School 10 times, but for 
#the 9th iteration, displays "Hi" before "Best School".

counting=0

while [ $counting -lt 10 ]
do
  if [ $counting -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( counting++ ))
done
