#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.new
grep -q "$localhost_mapping" /etc/hosts || echo "$localhost_mapping" >> /etc/hosts.new
grep -q "$facebook_mapping" /etc/hosts || echo "$facebook_mapping" >> /etc/hosts.new
cp -f ~/hosts.new /etc/hosts
